name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*messaging_service.py')
    - name: Analysing the lab2 code with pylint
      run: |
        pylint $(git ls-files 'Lab2-Bully/lab2.py')
    - name: Analysing the lab3 code with pylint
      run: |
        pylint $(git ls-files 'Lab3-Pub-Sub/lab3.py')